name: 'Validate AWS Secrets'
description: 'Validate required AWS secrets and CodeArtifact variables'

inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID secret'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key secret'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Validate required secrets
      shell: bash
      run: |
        echo "🔧 Validating required AWS secrets and CodeArtifact variables..."
        
        # Validar secrets AWS (passados como inputs)
        if [ -z "${{ inputs.aws-access-key-id }}" ]; then
          echo "❌ AWS_ACCESS_KEY_ID not set"
          exit 1
        fi
        if [ -z "${{ inputs.aws-secret-access-key }}" ]; then
          echo "❌ AWS_SECRET_ACCESS_KEY not set"
          exit 1
        fi
        
        # Validar variáveis CodeArtifact (variáveis de ambiente)
        if [ -z "${CA_DOMAIN}" ]; then
          echo "❌ CODEARTIFACT_DOMAIN not set"
          exit 1
        fi
        if [ -z "${CA_OWNER}" ]; then
          echo "❌ CODEARTIFACT_DOMAIN_OWNER not set"
          exit 1
        fi
        if [ -z "${CA_REPO}" ]; then
          echo "❌ CODEARTIFACT_REPOSITORY not set"
          exit 1
        fi
        
        echo "✅ All required AWS secrets and CodeArtifact variables are set"

