name: 'Configure AWS and CodeArtifact'
description: 'Authenticate AWS and login to CodeArtifact, setting npm registry'

inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID secret'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key secret'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Login to AWS CodeArtifact
      shell: bash
      run: |
        aws codeartifact login \
          --tool npm \
          --domain ${{ env.CA_DOMAIN }} \
          --domain-owner ${{ env.CA_OWNER }} \
          --repository ${{ env.CA_REPO }} \
          --region ${{ env.AWS_REGION }}
    
    - name: Set publish registry
      shell: bash
      run: |
        echo "🔧 Configuring npm to use CodeArtifact registry"
        npm config set registry $(aws codeartifact get-repository-endpoint \
          --domain ${{ env.CA_DOMAIN }} \
          --domain-owner ${{ env.CA_OWNER }} \
          --repository ${{ env.CA_REPO }} \
          --format npm \
          --query repositoryEndpoint \
          --output text)

